modified:   insert_abdata 	deleted:    wrapper_macos 	renamed:    wrapper_wifitests -> wrapper_wifi

diff --git a/wrapper_wifi b/wrapper_wifi
--- a/wrapper_wifi
+++ b/wrapper_wifi
@@ -14,6 +14,9 @@ ap_checking=true
 CELENO_SCRIPT="/home/lordberre-server/screens/ap_physcripting/./celeno_iw-snmp_forloop.sh"
 BROADCOM_SCRIPT="/home/lordberre-server/screens/ap_physcripting/3384_expect_forloop AC:BC:32:9B:EC:F5 macpro_5m-nlos"
 iperf3log="/var/log/iperf3_wrapper.log"
+IPERF3_SCRIPT="/home/chprobe/tcp_iperf3_clientv3.sh"
+SCREENLOGFILE="/home/lordberre-server/screens/usb0/sagem-rev3/screenlog.0"
+REDIRECT="/var/log/apdata.txt" # Output file (both Broadcom and Celeno)
 
 # Assign all vars
 AP_TYPE=false
@@ -25,6 +28,8 @@ CONSOLE=false
 IPERFSERVER=false
 TARGET=false
 downstream=false;upstream=false
+LABEL1=label1
+LABEL2=label2
 
 usage () {
 cat <<USAGE
@@ -40,13 +45,15 @@ How to use: $0 -4 or -6 must be specified.
     -r) Set AP radio ("5ghz" or "2.4ghz") (mandatory)
     -c) Set console name (Broadcom AP only)
     -i) Set AP IP (celeno AP only)
+    -y) Extra AP label 1
+    -z) Extra AP label 2
     -h) Show help
     -v) Increase verbosity
 
 USAGE
  }
 
-options='t:l:i:m:r:c:p:a:s:udhv'
+options='t:l:i:m:r:c:p:a:s:y:z:udhv'
 
 while getopts $options option
 do
@@ -63,6 +70,8 @@ do
         p  ) IPERFSERVER=${OPTARG};;
         a  ) TARGET=${OPTARG};;
         s  ) STA_TYPE=${OPTARG};;
+        y  ) LABEL1=${OPTARG};; # Temp
+        z  ) LABEL2=${OPTARG};; # Temp
         ? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
         :  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
         *  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
@@ -87,8 +96,8 @@ exit 1
 fi
 
 # Kill leftover scripts
-if [ $(pgrep -f 'celeno|3384_expect' | wc -l) -gt 1 ];then
-kill $(pgrep -f 'celeno|3384_expect') && echo Killed some leftover scripts..
+if [ $(pgrep -f 'celeno|3384_expect' | wc -l) -gt 8 ];then
+kill $(pgrep -f 'celeno|3384_expect ' | head -1) && echo Killed some leftover scripts..
 else echo "no leftover scripts detected (OK)"
 fi
 
@@ -99,21 +108,15 @@ elif [ $AP_RADIO = "2.4ghz" ]; then AP_RADIO=wlan0_0
 fi
 
 phy=vht # vht or ht
-REDIRECT="~/celenoap_data.txt" # Output file
 ###
 ##
 HOSTNAME="$(echo $STA_MAC | tr -d ':')"
-failcheck="$(snmpget -v2c -c private $IP .1.3.6.1.4.1.35604.2.3.101.0 | grep INT | wc -l)"
+failcheck="$(snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.101.0 | grep INT | wc -l)"
 
 ap_script () {
 if [ $ap_checking = true ];then
 	if [ $iperf3_check -ge 1 ];then # Check if iperf3 server is busy and continue if so
-	bash $CELENO_SCRIPT 1> /dev/null &
-	else echo "server is busy so not running AP script.."
-	fi
-else echo 'ap checking disabled.'
-fi
-}
+#	bash $CELENO_SCRIPT 1> /dev/null
 
 #### VHT TEMPLATE # Interal
 #vhtparse="snmpset -d -v2c -c private \$IP .1.3.6.1.4.1.35604.2.3.103.0 s \"iw \$RADIO station dump | grep -i \$STA_MAC -A 17 | egrep 'tx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e \"s/^/\$direction /\" | awk '{print \$1,\$3,\$7,\$10,\$11,\$12,\$13}' | tr -d 'MHz' | sed -e \"s/^/\$(date \"+%b %d %H:%M:%S\") \$HOSTNAME tx_linkstats_vht[1337]: /\" && iw \$RADIO station dump | grep -i \$STA_MAC -A 17 | egrep 'rx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e \"s/^/\$direction /\" | awk '{print \$1,\$3,\$7,\$10,\$11,\$12,\$13}' | tr -d 'MHz' | sed -e \"s/^/\$(date \"+%b %d %H:%M:%S\") \$HOSTNAME rx_linkstats_vht[1337]: /\" && iw \$RADIO station dump | grep -i \$STA_MAC -A 17 | egrep 'bytes|packets|retries|failed' | xargs | tr -d 'rx|tx|bytes|packets|retries|failed:' | sed -e \"s/^/\$(date \"+%b %d %H:%M:%S\") \$HOSTNAME iw_counters[1337]: /\" | tr -s ' '\""
@@ -137,31 +140,40 @@ if [ $failcheck 2> /dev/null -eq 1 ];then
 for x in {1..9};do
 
 # Fetch STA TX values
-snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'tx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e "s/^/$AP_LABEL /" | awk '{print $1,$3,$7,$10,$11,$12,$13}' | tr -d 'MHz' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME tx_linkstats_$phy[1337]: /" >> $REDIRECT
+snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'tx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e "s/^/$AP_LABEL /" | awk '{print $1,$3,$7,$10,$11,$12,$13}' | tr -d 'MHz' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME tx_linkstats_${phy}_ap[1337]: $LABEL1 $LABEL2 /" >> $REDIRECT
 
 # Fetch STA RX values
-snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'rx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e "s/^/$AP_LABEL /" | awk '{print $1,$3,$7,$10,$11,$12,$13}' | tr -d 'MHz' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME rx_linkstats_$phy[1337]: /" >> $REDIRECT
+snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'rx bitrate|signal:' | xargs | sed 's/\[.*\]//' | tr -d 'short|GI' | sed 's/\<VHT-NSS\>//g' | sed -e "s/^/$AP_LABEL /" | awk '{print $1,$3,$7,$10,$11,$12,$13}' | tr -d 'MHz' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME rx_linkstats_${phy}_ap[1337]: $LABEL1 $LABEL2 /" >> $REDIRECT
 
 # Fetch STA counters
-snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'bytes|packets|retries|failed' | xargs | tr -d 'rx|tx|bytes|packets|retries|failed:' | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME iw_counters[1337]: /" | tr -s ' ' >> $REDIRECT
+snmpset -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.103.0 s "iw $AP_RADIO station dump" && sleep 1 && snmpget -v2c -c private $AP_IP .1.3.6.1.4.1.35604.2.3.104.0 | grep -i $STA_MAC -A 17 | egrep 'bytes|packets|retries|failed' | xargs | tr -d 'rx|tx|bytes|packets|retries|failed:' | sed -e "s/^/$AP_LABEL /" | sed -e "s/^/$(date "+%b %d %H:%M:%S") $HOSTNAME iw_counters_ap[1337]: $LABEL1 $LABEL2 /" | tr -s ' ' >> $REDIRECT
 done
 
 else echo "Got an error, aborting" && exit 1
 fi
+        else echo "server is not busy so not running AP script.."
+        fi
+else echo 'ap checking disabled.'
+fi
+}
 
-fi 
+fi
 
 # Broadcom AP
 if [ $AP_TYPE = "broadcom" ]; then
-
-if [ $AP_RADIO = "5ghz" ];then AP_RADIO=wl1
-elif [ $AP_RADIO = "2.4ghz" ]; then AP_RADIO=wl0
+HOSTNAME="$(echo $STA_MAC | tr -d ':')"
+if [ $AP_RADIO = "5ghz" ];then AP_RADIO=wl1 # Only works with 4x4 AP
+elif [ $AP_RADIO = "2.4ghz" ]; then AP_RADIO=wl0 # Not implemented in local script
 fi
+
 
 ap_script () {
 if [ $ap_checking = true ];then
+count="$(( ( RANDOM % 9999 )  + 100 ))"
 	if [ $iperf3_check -ge 1 ];then # Check if iperf3 server is busy and continue if so
-	screen -S $CONSOLE -X stuff "/var/./phy.sh $AP_LABEL $AP_RADIO $STA_MAC \n"
+	screen -S $CONSOLE -X stuff "/var/./phy.sh $HOSTNAME $AP_RADIO $STA_MAC $LABEL1 $LABEL2 $count \n"
+#	sleep 1
+#	tail -300 $SCREENLOGFILE | grep $count >> $REDIRECT # Need proper func, tail is not enough
 	else echo "server is busy so not running AP script.."
 	fi
 else echo 'ap checking disabled.'
@@ -179,8 +191,20 @@ init_vars
 start_test () {
         if [ $ansible_check -ge 1 ] && [ $iperf3_check -le 0 ];then
 sleep 1
-ansible $TARGET -m shell -a "nohup /bin/bash $LOCALSCRIPT $IPERFSERVER &" >> $iperf3log
+ansible $TARGET -m shell -a "nohup /bin/bash $IPERF3_SCRIPT -4 $1 -f $IPERFSERVER &" >> $iperf3log
 sleep 1; init_vars
+# ap_script
+else echo "Aborting because target is either unreachable ($ansible_check) or the iperf3 server is busy ($iperf3_check)" && exit 1
+fi
+}
+
+mac_start_test () {
+        if [ $ansible_check -ge 1 ] && [ $iperf3_check -le 0 ];then
+sleep 1
+# Pipe to sleep because for some reason with some GWs, the whole iperf3 session is teared down when ansible is finished
+# Even though the script is completely daemonized with nohup/&
+ansible $TARGET -m shell -a "nohup /bin/bash $IPERF3_SCRIPT $IPERFSERVER | sleep 40" >> $iperf3log &
+sleep 2; init_vars
 # ap_script
 else echo "Aborting because target is either unreachable ($ansible_check) or the iperf3 server is busy ($iperf3_check)" && exit 1
 fi
@@ -193,7 +217,7 @@ busyfail=0
 while [ $checkbusy -eq 0 ]; do
 echo "no entry in the log, test must've failed, trying again.."
 sleep $[ ( $RANDOM % 1 ) + 3]s &&
-start_test
+if [ $STA_TYPE = mac ];then mac_start_test;else start_test;fi # WA for MAC
 checkbusy="$(tail -2 $iperf3log | grep SUCCESS | wc -l)"
 
 # Anti fail
@@ -208,17 +232,25 @@ done
 # Start doing stuff
 
 if [ $upstream = true ]; then 
-if [ $STA_TYPE = mac ];then 
+	if [ $STA_TYPE = mac ];then 
 # Macs have different scripts depending on direction so..
-LOCALSCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client-logstash.sh"
-fi
-elif [ $STA_TYPE = linux ];then echo 'aborting, not implemented' && exit 1
+IPERF3_SCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client-logstash.sh"
+mac_start_test;failcheck;ap_script
+elif [ $STA_TYPE = linux ];then
+start_test '-u';failcheck;ap_script
 elif [ $STA_TYPE = win ];then echo 'aborting, not implemented' && exit 1
-start_test;failcheck;ap_script
+else echo "wrong sta_type (must be either "mac", "linux", or "win - Aborting"" && exit 1
+	fi
 fi
 
 if [ $downstream = true ]; then
+	if [ $STA_TYPE = mac ];then
 # Macs have different scripts depending on direction so..
-LOCALSCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client_reversed-logstash.sh"
-start_test;failcheck;ap_script
+IPERF3_SCRIPT="/Users/testlabbet-pro/Labb-stuff/probes/mac_tcp_iperf3_client_reversed-logstash.sh"
+mac_start_test;failcheck;ap_script
+elif [ $STA_TYPE = linux ];then 
+start_test '-d';failcheck;ap_script
+elif [ $STA_TYPE = win ];then echo 'aborting, not implemented' && exit 1
+else echo "wrong sta_type (must be either "mac", "linux", or "win - Aborting"" && exit 1
+	fi
 fi
